apiVersion: apps/v1
kind: Deployment
metadata:
  name: snakefood
  namespace: snakefood
  labels:
    app: snakefood
    size: small
spec:
  replicas: 25
  selector:
    matchLabels:
      app: snakefood
  template:
    metadata:
      labels:
        app: snakefood
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: morsel
          image: registry.k8s.io/pause:3.9
